(defun gb/gopath ()
  (getenv "GOPATH"))

(defun gb/gb-project-root()
  (and (fboundp 'projectile-project-root)
       (projectile-project-p)
       (projectile-project-root)))

(defun gb/add-header()
  (when (eq major-mode 'go-mode)
	(let ((filetypes '("go"))
		  (filepath (file-name-directory (buffer-file-name)))
		  )
	  (when (member (file-name-extension (buffer-file-name)) filetypes)
		(spacemacs-buffer/set-mode-line concat("package " filepath))
		(spacemacs-buffer/set-mode-line "")
		))
	)
  )
